### PR TITLE
[Manta] Support sending batch calls

### PR DESCRIPTION
**Pull request by Dengjianping**
Ready to merge.
For resolve this issue #11

### CODE REVIEW

**Comment by ghzlatarev** [comment]
> Ready to merge.
> For resolve this issue #11

You can type:
```closes #11```
And it will link the issue automatically to the PR. If you also link it to the Manta-dev project, then it will move it automatically through the board. You can use other keywords like:
```resolves``` or ```fixes``` for the same effect pretty much.

**Comment by stechu** [comment]
Just a question rather than review:
Can a user sign transactions offline and send them in batch from the front-end?

**Comment by Dengjianping** [comment]
@ghzlatarev Thank!

**Comment by Dengjianping** [comment]
> Just a question rather than review:
> Can a user sign transactions offline and send them in batch from the front-end?

Good catch! I'll give it a try.

**Comment by Dengjianping** [comment]
> Just a question rather than review:
> Can a user sign transactions offline and send them in batch from the front-end?

I just add a function `create_signed_extrinsic` which can create a `offline` extrinsic, then got to front-end, navigate to `Developer/RPC calls/author/submitExtrinsic`, paste the `signed_extrinsic`, then submit it.

But maybe the word `offline` is not the way you think, it's not totally offline, we still need online node to create a client which will get metadata from the node for further usage.

**Review by zhenfeizhang — APPROVED** [review]
LGMT

**Pull request merged**
